In [1]:
# ============================================================
# 02 - NumPy & Vectorization
# ============================================================

import numpy as np
import time

# ============================================================
# 1. Create 2D Array
# ============================================================

arr = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])

print("Array:")
print(arr)

print("\nShape:")
print(arr.shape)

print("\nDimensions:")
print(arr.ndim)

print("\nData Type:")
print(arr.dtype)

# ============================================================
# 2. Row Means
# ============================================================

row_means = arr.mean(axis=1)

print("\nRow Means:")
print(row_means)

# ============================================================
# 3. Column Maxima
# ============================================================

column_maxima = arr.max(axis=0)

print("\nColumn Maxima:")
print(column_maxima)

# ============================================================
# 4. Column Normalization
# ============================================================

column_min = arr.min(axis=0)
column_max = arr.max(axis=0)

normalized = (
    (arr - column_min) /
    (column_max - column_min)
)

print("\nNormalized Array:")
print(normalized)

# ============================================================
# 5. Broadcasting
# ============================================================

column_means = arr.mean(axis=0)

centered = arr - column_means

print("\nColumn Means:")
print(column_means)

print("\nBroadcasting Result:")
print(centered)

# ============================================================
# 6. Vectorization
# ============================================================

large_arr = np.random.rand(1_000_000)

start = time.time()

vectorized = large_arr * 2

vectorized_time = time.time() - start

print("\nVectorized Time:")
print(vectorized_time)

# ============================================================
# 7. Python Loop
# ============================================================

start = time.time()

loop_result = [x * 2 for x in large_arr]

loop_time = time.time() - start

print("\nLoop Time:")
print(loop_time)

# ============================================================
# 8. Performance Comparison
# ============================================================

print("\nSpeedup:")
print(loop_time / vectorized_time)

Array:
[[10 20 30]
 [40 50 60]
 [70 80 90]]

Shape:
(3, 3)

Dimensions:
2

Data Type:
int64

Row Means:
[20. 50. 80.]

Column Maxima:
[70 80 90]

Normalized Array:
[[0.  0.  0. ]
 [0.5 0.5 0.5]
 [1.  1.  1. ]]

Column Means:
[40. 50. 60.]

Broadcasting Result:
[[-30. -30. -30.]
 [  0.   0.   0.]
 [ 30.  30.  30.]]

Vectorized Time:
0.0020172595977783203

Loop Time:
0.08862161636352539

Speedup:
43.93168656187212
