In [1]:
# ============================================================
# 02 - NumPy and Pandas
# Wine Quality Dataset
# ============================================================

import numpy as np
import pandas as pd

df = pd.read_csv("../data/WineQT.csv")

# ============================================================
# 1. NumPy Arrays
# ============================================================

print("NumPy Array Examples")

arr = np.array([10, 20, 30, 40, 50])

print("Array:", arr)
print("Shape:", arr.shape)
print("Dimensions:", arr.ndim)
print("Data type:", arr.dtype)

print("\nIndexing:")
print("First element:", arr[0])
print("Last element:", arr[-1])

print("\nSlicing:")
print("First three:", arr[:3])
print("Elements 2 to 4:", arr[1:4])

print("\nArray Operations:")
print("Mean:", np.mean(arr))
print("Median:", np.median(arr))
print("Standard deviation:", np.std(arr))
print("Minimum:", np.min(arr))
print("Maximum:", np.max(arr))

print("\nArithmetic:")
print("Array + 10:", arr + 10)
print("Array * 2:", arr * 2)

# ============================================================
# 2. NumPy 2D Arrays
# ============================================================

matrix = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

print("\n2D Array:")
print(matrix)

print("\nShape:", matrix.shape)
print("Dimensions:", matrix.ndim)

print("\nIndexing:")
print("First row:", matrix[0])
print("First column:", matrix[:, 0])
print("Element at row 2, column 3:", matrix[1, 2])

# ============================================================
# 3. Pandas Series
# ============================================================

print("\nPandas Series")

quality_series = df["quality"]

print(quality_series.head())
print("\nMean quality:", quality_series.mean())
print("Median quality:", quality_series.median())

# ============================================================
# 4. DataFrame Selection
# ============================================================

print("\nSelected Columns:")
print(df[["alcohol", "pH", "quality"]].head())

print("\nFirst 5 Rows:")
print(df.iloc[:5])

print("\nFirst 5 Rows and First 3 Columns:")
print(df.iloc[:5, :3])

# ============================================================
# 5. loc and iloc
# ============================================================

print("\nUsing loc:")
print(df.loc[:4, ["alcohol", "quality"]])

print("\nUsing iloc:")
print(df.iloc[:5, [11, 12]])

# ============================================================
# 6. Filtering
# ============================================================

high_quality = df[df["quality"] >= 7]

print("\nHigh Quality Wines:")
print(high_quality.head())

print("\nNumber of high-quality wines:", len(high_quality))

# Multiple conditions
high_alcohol_good = df[
    (df["alcohol"] > 10) &
    (df["quality"] >= 7)
]

print("\nWines with alcohol > 10 and quality >= 7:")
print(len(high_alcohol_good))

# ============================================================
# 7. Sorting
# ============================================================

print("\nTop 10 Wines by Alcohol:")
print(
    df.sort_values("alcohol", ascending=False)
    [["alcohol", "quality"]]
    .head(10)
)

# ============================================================
# 8. Value Counts
# ============================================================

print("\nQuality Counts:")
print(df["quality"].value_counts().sort_index())

# ============================================================
# 9. GroupBy
# ============================================================

print("\nAverage Alcohol by Quality:")
print(
    df.groupby("quality")["alcohol"]
    .mean()
    .round(2)
)

print("\nAverage pH by Quality:")
print(
    df.groupby("quality")["pH"]
    .mean()
    .round(2)
)

# ============================================================
# 10. Aggregation
# ============================================================

summary = df.groupby("quality").agg({
    "alcohol": ["mean", "min", "max"],
    "pH": ["mean", "min", "max"],
    "density": ["mean", "min", "max"]
})

print("\nGrouped Summary:")
display(summary.round(2))

# ============================================================
# 11. Duplicate Handling
# ============================================================

print("\nDuplicate rows:", df.duplicated().sum())

# ============================================================
# 12. Missing Value Handling
# ============================================================

print("\nMissing Values:")
print(df.isnull().sum())

# ============================================================
# 13. Creating a New Column
# ============================================================

df["alcohol_category"] = pd.cut(
    df["alcohol"],
    bins=[0, 9, 11, 20],
    labels=["Low", "Medium", "High"]
)

print("\nAlcohol Categories:")
print(df[["alcohol", "alcohol_category"]].head(10))

print("\nAlcohol Category Counts:")
print(df["alcohol_category"].value_counts())

NumPy Array Examples
Array: [10 20 30 40 50]
Shape: (5,)
Dimensions: 1
Data type: int64

Indexing:
First element: 10
Last element: 50

Slicing:
First three: [10 20 30]
Elements 2 to 4: [20 30 40]

Array Operations:
Mean: 30.0
Median: 30.0
Standard deviation: 14.142135623730951
Minimum: 10
Maximum: 50

Arithmetic:
Array + 10: [20 30 40 50 60]
Array * 2: [ 20  40  60  80 100]

2D Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Shape: (3, 3)
Dimensions: 2

Indexing:
First row: [1 2 3]
First column: [1 4 7]
Element at row 2, column 3: 6

Pandas Series
0    5
1    5
2    5
3    6
4    5
Name: quality, dtype: int64

Mean quality: 5.657042869641295
Median quality: 6.0

Selected Columns:
   alcohol    pH  quality
0      9.4  3.51        5
1      9.8  3.20        5
2      9.8  3.26        5
3      9.8  3.16        6
4      9.4  3.51        5

First 5 Rows:
   fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0            7.4              0.70         0.00             1.9      0.076

alcohol               pH             density           
           mean  min   max  mean   min   max    mean   min  max
quality                                                        
3          9.69  8.4  10.9  3.36  3.16  3.55     1.0  0.99  1.0
4         10.26  9.0  13.1  3.39  2.74  3.90     1.0  0.99  1.0
5          9.90  8.5  14.9  3.30  2.88  3.74     1.0  0.99  1.0
6         10.66  8.4  14.0  3.32  2.86  4.01     1.0  0.99  1.0
7         11.48  9.2  14.0  3.29  2.92  3.78     1.0  0.99  1.0
8         11.94  9.8  14.0  3.24  2.88  3.72     1.0  0.99  1.0


Duplicate rows: 0

Missing Values:
fixed acidity           0
volatile acidity        0
citric acid             0
residual sugar          0
chlorides               0
free sulfur dioxide     0
total sulfur dioxide    0
density                 0
pH                      0
sulphates               0
alcohol                 0
quality                 0
Id                      0
dtype: int64

Alcohol Categories:
   alcohol alcohol_category
0      9.4           Medium
1      9.8           Medium
2      9.8           Medium
3      9.8           Medium
4      9.4           Medium
5      9.4           Medium
6      9.4           Medium
7     10.0           Medium
8      9.5           Medium
9      9.2           Medium

Alcohol Category Counts:
alcohol_category
Medium    816
High      302
Low        25
Name: count, dtype: int64
